# Copyright 2013 The Chromium Authors. All rights reserved.
# Copyright 2013 Intel Corporation. All rights reserved.
# Copyright 2016-2017 LG Electronics, Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

{
  'targets': [
    {
      'target_name': 'webosport',
      'type': '<(component)',
      'variables': {
        'grit_out_dir': '<(SHARED_INTERMEDIATE_DIR)/webos',
        'version_script_path': '<(DEPTH)/build/util/version.py',
      },
      'dependencies': [
        '<(DEPTH)/base/base.gyp:base_static',
        '<(DEPTH)/base/third_party/dynamic_annotations/dynamic_annotations.gyp:dynamic_annotations',
        '<(DEPTH)/components/components.gyp:cdm_renderer',
        '<(DEPTH)/components/components.gyp:devtools_http_handler',
        '<(DEPTH)/components/components.gyp:media_capture_util',
        '<(DEPTH)/components/components.gyp:network_session_configurator',
        '<(DEPTH)/components/components.gyp:os_crypt',
        '<(DEPTH)/content/content.gyp:content_common',
        '<(DEPTH)/ozone/ui/webui/webui.gypi:webui',
        '<(DEPTH)/ozone/wayland/wayland.gyp:wayland_toolkit',
        '<(DEPTH)/third_party/WebKit/public/blink.gyp:blink',
        '<(DEPTH)/ui/aura/aura.gyp:aura',
        '<(DEPTH)/ui/base/ime/ui_base_ime.gyp:ui_base_ime',
        '<(DEPTH)/ui/events/events.gyp:dom_keycode_converter',
        '<(DEPTH)/ui/gfx/gfx.gyp:gfx_range',
        '<(DEPTH)/ui/ozone/ozone.gyp:ozone',
        '<(DEPTH)/ui/platform_window/webos/platform_window_webos.gyp:platform_window_webos',
        '<(DEPTH)/ui/views/controls/webview/webview.gyp:webview',
        '<(DEPTH)/ui/views/views.gyp:views',
        '<(DEPTH)/ui/wm/wm.gyp:wm',
        '<(DEPTH)/webos/webos_public.gyp:runtime',
        '<(DEPTH)/webos/webos_resources.gyp:webos_resources_pack',
      ],
      'include_dirs': [
        '.',
        '<(grit_out_dir)',
      ],
      'includes': [
        'webos_ui_views.gypi',
      ],
      'defines': [
        'CHROMIUM_VERSION=\"<!(python <(version_script_path) -f <(DEPTH)/chrome/VERSION -t "@MAJOR@.@MINOR@.@BUILD@.@PATCH@")\"',
      ],
      'conditions': [
        ['use_splash_screen==1', {
          'sources': [
            '<(DEPTH)/webos/renderer/webos_page_load_timing_render_frame_observer.cc',
            '<(DEPTH)/webos/renderer/webos_page_load_timing_render_frame_observer.h',
          ]
        }],
        ['enable_plugins==1', {
          'sources': [
            '<(DEPTH)/webos/browser/renderer_host/pepper/webos_pepper_host_factory.cc',
            '<(DEPTH)/webos/browser/renderer_host/pepper/webos_pepper_host_factory.h',
            '<(DEPTH)/webos/browser/renderer_host/pepper/webos_pepper_isolated_file_system_message_filter.cc',
            '<(DEPTH)/webos/browser/renderer_host/pepper/webos_pepper_isolated_file_system_message_filter.h',
          ],
        }],
      ],
      'sources': [
        '<(DEPTH)/webos/app/webos_content_main_delegate.cc',
        '<(DEPTH)/webos/app/webos_content_main_delegate.h',
        '<(DEPTH)/webos/app/webos_main.cc',
        '<(DEPTH)/webos/app/webos_main.h',
        '<(DEPTH)/webos/browser/browsing_data/webos_browsing_data_remover.cc',
        '<(DEPTH)/webos/browser/browsing_data/webos_browsing_data_remover.h',
        '<(DEPTH)/webos/browser/devtools/webos_devtools_delegate.cc',
        '<(DEPTH)/webos/browser/devtools/webos_devtools_delegate.h',
        '<(DEPTH)/webos/browser/net/webos_network_delegate.cc',
        '<(DEPTH)/webos/browser/net/webos_network_delegate.h',
        '<(DEPTH)/webos/browser/ui/aura/webos_browser_main_extra_parts_aura.cc',
        '<(DEPTH)/webos/browser/ui/aura/webos_browser_main_extra_parts_aura.h',
        '<(DEPTH)/webos/browser/webos_browser_context.cc',
        '<(DEPTH)/webos/browser/webos_browser_context.h',
        '<(DEPTH)/webos/browser/webos_browser_context_adapter.cc',
        '<(DEPTH)/webos/browser/webos_browser_context_adapter.h',
        '<(DEPTH)/webos/browser/webos_browser_main_extra_parts.h',
        '<(DEPTH)/webos/browser/webos_browser_main_parts.cc',
        '<(DEPTH)/webos/browser/webos_browser_main_parts.h',
        '<(DEPTH)/webos/browser/webos_browser_switches.cc',
        '<(DEPTH)/webos/browser/webos_browser_switches.h',
        '<(DEPTH)/webos/browser/webos_content_browser_client.cc',
        '<(DEPTH)/webos/browser/webos_content_browser_client.h',
        '<(DEPTH)/webos/browser/webos_http_user_agent_settings.cc',
        '<(DEPTH)/webos/browser/webos_http_user_agent_settings.h',
        '<(DEPTH)/webos/browser/webos_plugin_service_filter.cc',
        '<(DEPTH)/webos/browser/webos_plugin_service_filter.h',
        '<(DEPTH)/webos/browser/webos_url_request_context_getter.cc',
        '<(DEPTH)/webos/browser/webos_url_request_context_getter.h',
        '<(DEPTH)/webos/browser/webos_webview_renderer_state.cc',
        '<(DEPTH)/webos/browser/webos_webview_renderer_state.h',
        '<(DEPTH)/webos/common/webos_content_client.cc',
        '<(DEPTH)/webos/common/webos_content_client.h',
        '<(DEPTH)/webos/common/webos_event.cc',
        '<(DEPTH)/webos/common/webos_event.h',
        '<(DEPTH)/webos/common/webos_export.h',
        '<(DEPTH)/webos/common/webos_locales_mapping.cc',
        '<(DEPTH)/webos/common/webos_locales_mapping.h',
        '<(DEPTH)/webos/common/webos_localized_error.cc',
        '<(DEPTH)/webos/common/webos_localized_error.h',
        '<(DEPTH)/webos/common/webos_message_generator.cc',
        '<(DEPTH)/webos/common/webos_message_generator.h',
        '<(DEPTH)/webos/common/webos_view_messages.h',
        '<(DEPTH)/webos/common/webos_resource_delegate.cc',
        '<(DEPTH)/webos/common/webos_resource_delegate.h',
        '<(DEPTH)/webos/common/webos_watchdog.cc',
        '<(DEPTH)/webos/common/webos_watchdog.h',
        '<(DEPTH)/webos/renderer/webos_content_renderer_client.cc',
        '<(DEPTH)/webos/renderer/webos_content_renderer_client.h',
        '<(DEPTH)/webos/renderer/webos_render_view_observer.cc',
        '<(DEPTH)/webos/renderer/webos_render_view_observer.h',
        '<(DEPTH)/webos/renderer/net/template_builder.cc',
        '<(DEPTH)/webos/renderer/net/template_builder.h',
        '<(DEPTH)/webos/renderer/net/webos_net_error_helper.cc',
        '<(DEPTH)/webos/renderer/net/webos_net_error_helper.h',
        '<(DEPTH)/webos/webapp_window.cc',
        '<(DEPTH)/webos/webapp_window.h',
        '<(DEPTH)/webos/webapp_window_base.cc',
        '<(DEPTH)/webos/webapp_window_base.h',
        '<(DEPTH)/webos/webapp_window_delegate.h',
        '<(DEPTH)/webos/webos_platform.cc',
        '<(DEPTH)/webos/webview.cc',
        '<(DEPTH)/webos/webview.h',
        '<(DEPTH)/webos/webview_base.cc',
        '<(DEPTH)/webos/webview_base.h',
        '<(DEPTH)/webos/webview_delegate.h',
        '<(DEPTH)/webos/webview_profile.cc',
        '<(DEPTH)/webos/webview_profile.h',
        '<(DEPTH)/webos/window_group_configuration.cc',
        '<(DEPTH)/webos/window_group_configuration.h',
      ],
    },
  ]
}
